name: Publish

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: git config --global user.email "${{secrets.GIT_EMAIL}}"
      - run: git config --global user.name "${{secrets.GIT_NAME}}"
      - run: npm version patch --force
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
